GET http://localhost:8080/hello
Accept: application/json

###

POST http://localhost:8080/hello/post
Content-Type: application/x-www-form-urlencoded

name=TEST
###

GET http://localhost:8080/test/list

###

GET http://localhost:8080/redis/set/434/123
Accept: application/json

###

GET http://localhost:8080/redis/get/167643591508889600
Accept: application/json

###
